@startuml
'https://plantuml.com/class-diagram

package "data" {

class Session {
json
? game_info
---
+ From json storage
getName()
getPath()
getOriginName(
getLauncher()
getPlatform()
getCustomCommand()
getNote()
getWWW()
getTips()
---
}

class SessionList {
json_sessions
storage
}

SessionList "1" *-> "0..N" Session : sessions
}

@enduml